config/routes.rb
Rails.application.routes.draw do

  get 'users/add'
  post 'users/create'
  get 'users/show'
  resources :posts

  root 'posts#index'

  get 'post/action/:task' => 'posts#action'
  get 'posts/:id' => 'posts#show'

    get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

    namespace :admin do
       resources :posts
    end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    #@post = Post.first
    #render action: :show
    #redirect_to action: :show, id: Post.first.id
  end
  # GET /post/action/task
  def action
    @task =  params[:task]
    @var =  params[:var]
    @format = params[:format]

    if cookies[:token].nil?
      cookies[:token]='NKUSE3'
    end
      @token=cookies[:token]

    if session[:var].nil?
      session[:var]='Session Var'
    end
      @var=session[:var]

    if flash[:error_text].nil?
      flash[:error_text]='Error Text'
    end

    @actions=['review','publish','clean']

    render status: 404
  end

  # GET /posts/1
  # GET /posts/1.json

  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :publish_date, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def add
  end

  def create
    name=params[:name]
    lastname=params[:lastname]
    age=params[:age]

    puts name,lastname,age

    redirect_to action: :show

  end

  def remove
  end

  def destroy
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>Bienvenido</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publish_date %><br>
    <%= f.date_select :publish_date %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/action.html.erb
<h1>Actions:</h1>

<p><%= @task %> </p>

<p><%= @var %> </p>

<h2><%= @token %> </h2>

<h2><%= flash[:$error_text] %> </h2>

<ul>
  <% @actions.each do |action| %>
       <li><%= action %> </li>
  <% end %>
</ul>

  <% if @task.include? 'a' %>
      <p> @task include a<p/>
  <% end %>
      <p><%= @task.upcase %></p>


<%= @local %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% content_for :head do %>
    <title>Indice de Post</title>
<% end %>
<p id="notice"><%=flash[:error_text] %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Publish date</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.publish_date %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<%= link_to 'New User', users_add_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @post.publish_date %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/add.html.erb
<h1><%= t('users.add') %> </h1>
<p>We need name,lastname, age</p>

<%= form_tag users_create_path do %>
    <%= label_tag 'name',t('users.name')  %>
    <%= text_field_tag 'name' %>
    <%= label_tag 'lastname',t('users.lastname')  %>
    <%= text_field_tag 'lastname' %>
    <%= label_tag 'age',t('users.age')  %>
    <%= text_field_tag 'age' %>
    <%= submit_tag t('users.send')  %>

<% end -%>

<%= link_to 'Posts', posts_path %>

<%= image_tag("vitopavo.jpg", size:"480x480", alt:"banner") %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/remove.html.erb
<h1>Users#remove</h1>
<p>Find me in app/views/users/remove.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>